### ISSUE TITLE
Build failed because AgoraChat is missing a required architecture

### ISSUE THREAD

**Issue by aleos** [AgoraIO/AgoraChat_iOS#12]
I included Agora Chat SDK in my project and can't build it for simulator anymore. I get the error:
<img width="515" alt="image" src="https://github.com/AgoraIO/AgoraChat_iOS/assets/176364/6e8cfaa9-5719-40a4-93bd-5d12a38f52d3">
Could you please support the simulator architecture?

**Comment by lixm1988** [comment]
Until now Agora_Chat_iOS does't support arm64-simulator architecture.If you want to build it for simulator, you need enable rosetta and exclude arm64-simulator.
On Xcode 14.3,you can choose rosetta as this steps
![image](https://github.com/AgoraIO/AgoraChat_iOS/assets/24401006/ec8238d1-3cf0-4f0c-a0ca-6918dfdc0011)

**Comment by maxxfrazer** [comment]
@lixm1988 could we add the architecture in the next release, or is there something preventing us from doing so?

Apple is dropping rosetta support for Xcode:
https://developer.apple.com/documentation/technotes/tn3117-resolving-build-errors-for-apple-silicon#Update-pre-compiled-libraries-with-Apple-silicon-support
Noted from the above link:
> Don’t launch Xcode using Rosetta to resolve these errors.

More info: https://news.ycombinator.com/item?id=35079270

**Comment by lixm1988** [comment]
@maxxfrazer  Agora_Chat_iOS SDK depends on a library supported by a third Team.The library does not include  arm64-simulator architecture.We have contacted them, and they will support arm64-simulator later

**Comment by maxxfrazer** [comment]
As Xcode is beginning to drop support, let’s see if they can bring up the timeline on it. Will message you separately

**Comment by aleos** [comment]
Enabling rosetta looks like too radical a change for my project. I made my project build by providing a 'stub' version of the chat model struct for simulator that doesn't actually use AgoraChat. It's currently ok as a temporary solution. But I hope that soon it will be possible to add support for the arm64 simulator, and I look forward to any information about this.

**Comment by aleos** [comment]
Are there any updates about the architecture support? I have found a workaround for this problem, but it would be better to remove it and use the built-in solution.

**Comment by lixm1988** [comment]
We will support arm64-simulator  in the next release and fix this problem.

**Comment by aleos** [comment]
That's great news! Is there any rough estimate when the next release might be rolled out?

**Comment by lixm1988** [comment]
We plan to release the next version around mid-August. Any questions, please contact us.

**Comment by aleos** [comment]
Do you have any news?

**Comment by lixm1988** [comment]
> Do you have any news?

Sorry to keep you waiting for so long, there are still some unfinished documentation work in the 1.2.0 Release version. You can integrate the 1.2.0-beta version first.
![image](https://github.com/AgoraIO/AgoraChat_iOS/assets/24401006/7457fa03-91d2-4109-bc5b-c1cc3fc744e6)

**Comment by aleos** [comment]
Thank you! I'll try the beta version

**Comment by aleos** [comment]
Updated to v1.2. The issue is fixed. Thank you!
